const fileInput=document.getElementById("fileInput"),dropzone=document.getElementById("dropzone"),previewWrap=document.getElementById("previewWrap"),sourcePreview=document.getElementById("sourcePreview"),fileName=document.getElementById("fileName"),effect=document.getElementById("effect"),framesInput=document.getElementById("frames"),durationInput=document.getElementById("duration"),frameValue=document.getElementById("frameValue"),durationValue=document.getElementById("durationValue"),generateButton=document.getElementById("generate"),downloadButton=document.getElementById("download"),status=document.getElementById("status"),result=document.getElementById("result"),resultSize=document.getElementById("resultSize");
const targetImage=new Image();targetImage.src="assets/trump-target.svg";let sourceImage=null,resultUrl=null;
framesInput.addEventListener("input",()=>frameValue.textContent=framesInput.value);durationInput.addEventListener("input",()=>durationValue.textContent=`${durationInput.value}ms`);
fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];if(f)loadFile(f)});
["dragenter","dragover"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.add("dragging")}));["dragleave","drop"].forEach(t=>dropzone.addEventListener(t,e=>{e.preventDefault();dropzone.classList.remove("dragging")}));
dropzone.addEventListener("drop",e=>{const f=e.dataTransfer.files?.[0];if(f)loadFile(f)});generateButton.addEventListener("click",generateGif);downloadButton.addEventListener("click",()=>{if(!resultUrl)return;const a=document.createElement("a");a.href=resultUrl;a.download=`trumpify-${Date.now()}.gif`;a.click()});
function loadFile(file){if(!file.type.startsWith("image/")){status.textContent="Please choose an image file.";return}fileName.textContent=file.name;status.textContent="Image loaded. Ready to generate.";const reader=new FileReader();reader.onload=()=>{sourceImage=new Image();sourceImage.onload=()=>{sourcePreview.src=reader.result;previewWrap.classList.remove("hidden");dropzone.classList.add("hidden");generateButton.disabled=false};sourceImage.src=reader.result};reader.readAsDataURL(file)}
function fitSize(w,h,max=720){const s=Math.min(1,max/Math.max(w,h));return{width:Math.max(1,Math.round(w*s)),height:Math.max(1,Math.round(h*s))}}
function drawCover(ctx,img,w,h,scale=1,ox=0,oy=0){const r=img.width/img.height,cr=w/h;let dw,dh;if(r>cr){dh=h*scale;dw=dh*r}else{dw=w*scale;dh=dw/r}ctx.drawImage(img,(w-dw)/2+ox,(h-dh)/2+oy,dw,dh)}
function drawFrame(ctx,w,h,p){ctx.clearRect(0,0,w,h);ctx.fillStyle="#08090c";ctx.fillRect(0,0,w,h);let s=1,x=0,y=0;if(effect.value==="zoom")s=1+p*.08;if(effect.value==="shake"){x=Math.sin(p*Math.PI*12)*(1-p)*7;y=Math.cos(p*Math.PI*10)*(1-p)*4}drawCover(ctx,sourceImage,w,h,s,x,y);ctx.save();ctx.globalAlpha=p;if(effect.value==="zoom"){const ts=1+(1-p)*.06;ctx.translate(w/2,h/2);ctx.scale(ts,ts);ctx.translate(-w/2,-h/2)}drawCover(ctx,targetImage,w,h);ctx.restore()}
async function generateGif(){if(!sourceImage)return;generateButton.disabled=true;downloadButton.disabled=true;status.textContent="Generating GIF...";result.innerHTML='<div class="empty">Rendering frames...</div>';resultSize.textContent="";if(!targetImage.complete)await new Promise(r=>targetImage.onload=r);const size=fitSize(sourceImage.width,sourceImage.height),canvas=document.createElement("canvas");canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext("2d"),count=Number(framesInput.value),delay=Number(durationInput.value),gif=new GIF({workers:2,quality:10,width:size.width,height:size.height,workerScript:"https://cdn.jsdelivr.net/npm/gif.js@0.2.0/dist/gif.worker.js"});for(let i=0;i<count;i++){drawFrame(ctx,size.width,size.height,i/(count-1));gif.addFrame(ctx,{copy:true,delay});if(i%3===0){status.textContent=`Rendering frame ${i+1} of ${count}...`;await new Promise(requestAnimationFrame)}}gif.on("progress",p=>status.textContent=`Encoding GIF ${Math.round(p*100)}%...`);gif.on("finished",blob=>{if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);const img=document.createElement("img");img.src=resultUrl;img.alt="Generated Trumpify GIF";result.innerHTML="";result.appendChild(img);resultSize.textContent=formatBytes(blob.size);status.textContent="GIF ready.";downloadButton.disabled=false;generateButton.disabled=false});gif.render()}
function formatBytes(b){if(b<1024)return`${b} B`;if(b<1048576)return`${(b/1024).toFixed(1)} KB`;return`${(b/1048576).toFixed(1)} MB`}
